name: realm_ffigen
description: >- 
  A dev package for generating realm bindings.

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  ffigen: ^5.0.0

ffigen:
  name: RealmLibrary
  output: "../lib/src/native/realm_bindings.dart"
  description: "Binding for the realm-core C API"
  headers:
    entry-points:
      - 'entrypoint.h'
    include-directives: #generate only for these headers
      - '**src**.h'
  compiler-opts:  
    - '-DRLM_NO_ANON_UNIONS'
    - '-DFFI_GEN'
    - '-I../src'
    - '-I../src/realm-core/src'
    - '-I../src/dart-dl'
  sort: true
  functions:
    exclude:
      - '_.*' #exclude all starting with _
    symbol-address:
      include:
        - 'realm_dart_.*'
  globals:
    exclude:
      - 'RLM_.*' #exlude RLM_ globals constants since they are not exported from binary
